### ISSUE TITLE
Zero or one based index handling consolidation on the Matlab side

### ISSUE THREAD

**Issue by mpsonntag** [G-Node/nix-mx#150]
Matlab uses 1-based indexing opposed to 0 based indexing in C++. Currently we have a mixture of 0-based indexing and 1-based indexing in the Matlab side of the bindings, which should be unified to either one or the other.
- If we want to support 1-based indexing, the index manipulation and eventual error messages should be handled on the Matlab side.
- If we want to support 0-based indexing, we should add notes to all docstrings, since this deviates from the Matlab norm.

**Comment by achilleas-k** [comment]
I vote consistency with Matlab norm: 1-based indexing
