### ISSUE TITLE
MacOS build

### ISSUE THREAD

**Issue by vagechirkov** [G-Node/nix-mx#177]
Dear All,

After this update #175 I still can't build for MAC OS (Mojave 10.14.4) without setting these paths manually:

//Path to a file.
NIX_INCLUDE_DIR:PATH=/usr/local/Cellar/nixio/1.4.3/include

//Path to a library.
NIX_LIBRARY:FILEPATH=/usr/local/Cellar/nixio/1.4.3/lib/libnix.dylib

I have tried both `cd build; cmake ..` and `cd build; cmake ..  -DBUILD_STATIC=OFF` 

Terminal output and log file:
[CMakeOutput.log](https://github.com/G-Node/nix-mx/files/5052537/CMakeOutput.log)

```bash
MacBook-Pro-Valerij:nix valery$ git clone https://github.com/g-node/nix-mx.git
Cloning into 'nix-mx'...
remote: Enumerating objects: 4799, done.
remote: Total 4799 (delta 0), reused 0 (delta 0), pack-reused 4799
Receiving objects: 100% (4799/4799), 2.01 MiB | 1.23 MiB/s, done.
Resolving deltas: 100% (3682/3682), done.
MacBook-Pro-Valerij:nix valery$ cd nix-mx
MacBook-Pro-Valerij:nix-mx valery$ mkdir build
MacBook-Pro-Valerij:nix-mx valery$ cd build; cmake ..
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost: /usr/local/lib/cmake/Boost-1.72.0/BoostConfig.cmake (found suitable version "1.72.0", minimum required is "1.49.0") found components: date_time regex program_options system filesystem 
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/local/Cellar/hdf5/1.12.0/lib/libhdf5.a;/usr/local/opt/szip/lib/libsz.dylib;/usr/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib (found version "1.12.0") found components: C 
-- Matlab found at /Applications/MATLAB_R2018a.app/extern/include
CMake Error at /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find NIX (missing: NIX_LIBRARY NIX_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindNIX.cmake:37 (find_package_handle_standard_args)
  CMakeLists.txt:70 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/valery/Downloads/nix/nix-mx/build/CMakeFiles/CMakeOutput.log".
MacBook-Pro-Valerij:build valery$ cmake .. -DBUILD_STATIC=OFF
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Matlab found at /Applications/MATLAB_R2018a.app/extern/include
CMake Error at /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find NIX (missing: NIX_LIBRARY NIX_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindNIX.cmake:37 (find_package_handle_standard_args)
  CMakeLists.txt:70 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/valery/Downloads/nix/nix-mx/build/CMakeFiles/CMakeOutput.log".
```

Best regards,
Valerii

**Comment by jgrewe** [comment]
@vagechirkov thanks for the report. I won't have time to have a really detailed look into it before next week, but from what you write, the problem can be solved with setting the libs and includes manually.

One question would be how did you install the nix-c++ library? Did you build it locally, or did you use homebrew?

**Comment by vagechirkov** [comment]
@jgrewe I have used homebrew. Setting these paths manually works for me. Unfortunately, this is not clear from the instruction.

**Comment by jgrewe** [comment]
@vagechirkov this is not as it should be. In the best of worlds cmake should be able to find the installed libraries without the need of manual interference.  I wonder what makes my environment different from yours. I will have a look and try to fix this...

**Comment by jgrewe** [comment]
@vagechirkov it took me a little longer to find the time for it. On my system I tried static as well as dynamic linking and succeeded in both configurations. Before I tried, I made sure that there is no manually installed or brewed nix-cpp library on my system (check ``/usr/local/lib`` or ``/usr/local/include``). Then I did a fresh installation of either the dynamic ``brew install nixio`` or the static version ``brew install nixio-static`` and then configured nix-mx build with either ``cmake .. -DBUILD-STATIC=OFF`` for the dynamic version or ``cmake .. `` for static building. Configurations succeeded in both cases and both resulting nix-mx versions work for me. 
It would be great if you could give it a try at some point. Before you try please wait for pull-request https://github.com/G-Node/homebrew-pkg/pull/4 to be merged. This installs the latest nix release which in turn fixes some problems with the installation of the static nix library. Cheers and thanks again!

**Comment by vagechirkov** [comment]
@jgrewe I have built the package without errors using both static and dynamic options! All tests succeeded!

**Comment by jgrewe** [comment]
perfekt, thank you @vagechirkov ! Closing this issue for now ;)
